config/routes.rb
# START:routes
Saveup::Application.routes.draw do |map|
  
  resources :businesses

  resources :goals do
    resources :credits
  end
# END:routes

  root :to => "goals#index"

  map.resources :sessions, :users

  match 'login'  => 'sessions#new',     :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'join'   => 'users#new',        :as => :join
  match 'about'  => 'info#index',       :as => :about

# START:routes

end
# END:routes

app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :goal
  
  validates_presence_of :name, :amount
  validates_numericality_of :amount, :greater_than => 0
  
  def to_xml(options={})
    default_serialization_options(options)
    super(options)
  end
  
  def to_json(options={})
    default_serialization_options(options)
    super(options)
  end
  
protected

  def default_serialization_options(options={})
    options[:only] = [:id, :name, :goal_id, :amount, :updated_at, :created_at]
  end
  
end

app/controllers/credits_controller.rb
# START:nested
class CreditsController < ApplicationController
# END:nested  
  before_filter :login_required
# START:nested

  before_filter :find_goal
# END:nested
  
  def index
    @credits = @goal.credits.all

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @credits }
      format.json { render :json => @credits }
    end
  end
# START:nested

  def show
    @credit = @goal.credits.find(params[:id])

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @credit }
      format.json { render :json => @credit }
    end
  end
# END:nested

  def new
    @credit = @goal.credits.build

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @credit }
      format.json { render :json => @credit }
    end
  end

  def edit
    @credit = @goal.credits.find(params[:id])
  end

  def create
    @credit = @goal.credits.build(params[:credit])

    respond_to do |format|
      if @credit.save
        format.html { redirect_to @goal }
        format.xml  { render :xml => @credit, :status => :created, :location => [@goal, @credit] }
        format.json { render :json => @credit, :status => :created, :location => [@goal, @credit] }
        format.js
      else
        format.html { render :action => "new" }
        format.xml  { render :xml  => @credit.errors, :status => :unprocessable_entity }
        format.json { render :json => @credit.errors, :status => :unprocessable_entity }
        format.js do
          render :update do |page| 
            flash[:error] = @credit.errors.full_messages.to_sentence
            page.redirect_to @goal 
          end
        end
      end
    end
  end

  def update
    @credit = @goal.credits.find(params[:id])

    respond_to do |format|
      if @credit.update_attributes(params[:credit])
        format.html { redirect_to @goal }
        format.any(:xml, :json) { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml  => @credit.errors, :status => :unprocessable_entity }
        format.json { render :json => @credit.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @credit = @goal.credits.find(params[:id])
    @credit.destroy

    respond_to do |format|
      format.html { redirect_to @goal }
      format.js   { render 'create'}
      format.any(:xml, :json) { head :ok }
    end
  end
# START:nested
  
protected

  def find_goal
    @goal = current_user.goals.find(params[:goal_id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = "Invalid goal."
    redirect_to @goal
  end
  
end
# END:nested

app/views/credits/_form.html.erb
<%= labeled_form_for([@goal, @credit]) do |f| %>
<fieldset>  
  <%= f.error_messages %>
  <%= f.text_field :name %>
  <%= f.text_field :amount, :size => 10 %>  
  <%= f.submit %>
</fieldset>
<% end %>

app/views/credits/edit.html.erb
<% banner "Edit Credit for #{h(@goal.name)}" %>

<%= render 'form' %>

app/views/credits/index.html.erb
<% banner "#{h(@goal.name)} Credits", 
          link_to('Create new credit', new_goal_credit_path(@goal)) %>

<%= render 'goals/credits', :credits => @goal.credits, :goal => @goal %>

app/views/credits/new.html.erb
<% banner "New #{@goal.name} Credit" %>

<%= render 'form' %>

app/views/credits/show.html.erb
<% banner "#{@goal.name} Credit", 
  link_to('Edit', edit_goal_credit_path(@goal, @credit)),
  link_to('Delete', goal_credit_path(@goal, @credit), 
           :confirm => 'Sure?', :method => :delete) %>

<table id="credits-table" cellpadding="0" cellspacing="0">
  <tr>
    <td class="name">
      <%= link_to @credit.name, 
                  goal_credit_path(@credit.goal, @credit) %>
    </td>
    <td class="amount">
      <%= number_to_currency(@credit.amount) %>
    </td>
  </tr>
</table>

<p>
<%= link_to 'All credits for this goal', 
            goal_credits_path(@goal) %>
</p>