config/routes.rb
# START:routes
Saveup::Application.routes.draw do |map|
  
  resources :businesses

  resources :goals do
    resources :credits
  end
# END:routes

  root :to => "goals#index"

  map.resources :sessions, :users

  match 'login'  => 'sessions#new',     :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'join'   => 'users#new',        :as => :join
  match 'about'  => 'info#index',       :as => :about

# START:routes

end
# END:routes

app/models/goal.rb
class Goal < ActiveRecord::Base
  
  belongs_to :user
  has_many :credits, :order => 'updated_at', :dependent => :destroy
  
  validates_presence_of :name, :amount
  validates_numericality_of :amount, :greater_than => 0.0

  def self.search(query)
    where("name like ?", "%#{query}%")
  end
  
  def saved
    credits.inject(0) {|sum, credit| sum + credit.amount }
  end
  
  def remaining
    amount - saved
  end
  
  def reached?
    saved >= amount
  end
  
  def to_xml(options={})
    default_serialization_options(options)
    super(options)
  end
  
  def to_json(options={})
    default_serialization_options(options)
    super(options)
  end
  
protected

  def default_serialization_options(options={})
    options[:only] = [:id, :name, :amount, :updated_at, :created_at]
    options[:methods] = [:saved, :remaining] if self.amount
  end
  
end

app/controllers/goals_controller.rb
# START:authentication
class GoalsController < ApplicationController

  before_filter :login_required

  def index
    @goals = current_user.goals.all

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @goals }
      format.json { render :json => @goals }
    end
  end

# END:authentication

  def show
    @goal = current_user.goals.find(params[:id])
    @credit = Credit.new

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @goal }
      format.json { render :json => @goal }
    end
  end
  
  def new
    @goal = current_user.goals.build

    respond_to do |format|
      format.html
      format.xml  { render :xml  => @goal }
      format.json { render :json => @goal }
    end
  end

  def edit
    @goal = current_user.goals.find(params[:id])
  end

  def create
    @goal = current_user.goals.build(params[:goal])

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @goal }
        format.xml  { render :xml  => @goal, :status => :created, :location => @goal }
        format.json { render :json => @goal, :status => :created, :location => @goal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @goal.errors, :status => :unprocessable_entity }
        format.json { render :xml => @goal.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @goal = current_user.goals.find(params[:id])

    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @goal }
        format.any(:xml, :json) { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml  => @goal.errors, :status => :unprocessable_entity }
        format.json { render :json => @goal.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @goal = current_user.goals.find(params[:id])
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to(goals_url) }
      format.any(:xml, :json) { head :ok }
    end
  end
    
# START:authentication
end
# END:authentication

app/helpers/goals_helper.rb
module GoalsHelper
  
  def goal_total_class(goal)
    goal.reached? ? 'over' : 'under'
  end

end

app/views/goals/_credits.html.erb
<table id="credits-table" cellpadding="0" cellspacing="0">
<% credits.each do |credit| -%>
  <tr>
    <td class="name">
      <%= link_to credit.name, 
                  edit_goal_credit_path(credit.goal, credit) %>
    </td>
    <td class="amount">
      <%= number_to_currency(credit.amount) %>
    </td>
    <td class="delete">
      <%= link_to 'x', goal_credit_url(goal, credit),
                       :method  => :delete,
                       :remote  => true, 
                       :class => 'destructive' %>
    </td>
  </tr>
<% end -%>
</table>

app/views/goals/_form.html.erb
<%= labeled_form_for @goal do |f| %>
<fieldset>  
  <%= f.error_messages %>
  <%= f.text_field :name %>
  <%= f.text_field :amount, :size => 10 %>  
  <%= f.submit %>
</fieldset>
<% end %>

app/views/goals/_summary.html.erb
<span class="goal_saved">
  <%= number_to_currency(goal.saved) %> 
</span>
<span class="goal_amount">
  of <%= number_to_currency(goal.amount) %>
</span>
<span class="<%= goal_total_class(goal) %>">
  (<%= number_to_currency(goal.remaining.abs) %>)
</span>

app/views/goals/edit.html.erb
<% banner "Edit Goal" %>

<%= render 'form' %>

app/views/goals/index.html.erb
<% banner 'Goals', link_to('Create new goal', new_goal_path) %>
           
<% unless @goals.any? %>
<p class="empty">
  No goals (yet).  Go on, <%= link_to('create one already!', new_goal_path) %>
</p>
<% end %>
  
<table id="goals-table" cellpadding="0" cellspacing="0">
<% @goals.each do |goal| %>
  <tr>
    <td class="name">
      <%= link_to goal.name, goal %>
    </td>
    <td class="goal">
      <span class="goal_saved">
        <%= number_to_currency(goal.saved) %> 
      </span>
      <span class="goal_amount">
        of <%= number_to_currency(goal.amount) %>
      </span>
    </td>
    <td class="remaining">
      <span class="<%= goal_total_class(goal) %>">
        (<%= number_to_currency(goal.remaining.abs) %>)
      </span>
    </td> 
  </tr>
<% end %>
</table>

app/views/goals/new.html.erb
<% banner "New Goal" %>

<%= render 'form' %>

app/views/goals/show.html.erb
<% banner "Goal: #{h(@goal.name)}", 
  link_to('Edit', edit_goal_path(@goal)),
  link_to('Delete', @goal, :confirm => 'Sure?', :method => :delete) %>

<div id="goal">

<div id="summary">
  <%= render 'summary', :goal => @goal %>
</div>

<div class="break"></div>

<div id="credits">
  <% if @goal.credits.any? %>  
    <%= render 'credits', :credits => @goal.credits, :goal => @goal %>
  <% else %>
    <p class="empty">
      No goal credits (yet).  Go on, add one already!
    </p>
  <% end %>
</div>

<div class="break"></div>

<h3>Add a credit</h3>

<%= form_for([@goal, @credit], :remote => true) do |f| %>
  <p class="credit-form">
    $<%= f.text_field :amount, :size => 6 %> 
    <strong>on</strong>
    <%= f.text_field :name %>
  </p>
  <%= f.submit 'Add this credit' %> or 
  <%= cancel_link goals_path %>
<% end %>

</div>