config/routes.rb
# START:routes
Saveup::Application.routes.draw do |map|
  
  resources :businesses

  resources :goals do
    resources :credits
  end
# END:routes

  root :to => "goals#index"

  map.resources :sessions, :users

  match 'login'  => 'sessions#new',     :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'join'   => 'users#new',        :as => :join
  match 'about'  => 'info#index',       :as => :about

# START:routes

end
# END:routes

app/controllers/info_controller.rb
class InfoController < ApplicationController
  
  def index
  end
    
end

app/views/info/index.html.erb
<div id="about">
  
<p>
  If you skipped buying those fancy lattes this week, how much closer would you be to affording a
  tropical vacation this summer? How many lattes would you give up if you were to take that vacation?
</p>
<p>
  Money is an abstract concept. When faced with the temptation to spend it now or save it for later,
  we often don't realize what we're giving up or what we're gaining. We spend our money today. We talk
  about saving it for the future. And in the meantime, we complain that we can't afford the
  things we're most interested in.
</p>
<p>
  <strong>Save Up makes money more concrete by helping you think of it in terms of
  substitutions.</strong> You say &quot;I like vacations in the Bahamas, gadgets made by Apple, and
  charitable causes.&quot; Then, when you're tempted to buy something, that thing is translated in
  terms of the things you are interested in. By thinking about our spending differently&mdash;by
  comparing all the things we're interested in&mdash;perhaps we can make better decisions.
</p>
<p>
  The idea for this app was inspired by Dan Ariely's <a href="http://bigthink.com/ideas/17458">Making
  Money Less Abstract</a> video on <em>Big Think</em>. It's a good video. You should watch it:
</p>

<div class="video">
<%= link_to image_tag('video.png', :width => 514, :height => 288),
            'http://bigthink.com/ideas/17458', :target => 'new' %>
</div>

<p style="text-align: center; font-size: 1.75em;">
  <%= link_to "Create an account", join_path %> to start recording credits toward your money goals!
</p>

</div>